### ISSUE TITLE
Script seem to not work in japanese games.

### ISSUE THREAD

**Issue by evertonstz** [BertrandHustle/psx_scraper#1]
Tested on Nekketsu Oyako [NPJJ00763] and Puyo Puyo Box [NPJJ00773], both return a blank string.

**Comment by BertrandHustle** [comment]
I _think_ this is because utf-8 can't handle the Japanese text in the JP eboot files.  

@evertonstz do you happen to know what encoding those use? I'm gonna test/look for possible encodings in the meantime.

**Comment by BertrandHustle** [comment]
It's UTF-8 but I was testing with an illegal multibyte sequence, nvm.  Disregard previous comment.

**Comment by evertonstz** [comment]
> 
> 
> I _think_ this is because utf-8 can't handle the Japanese text in the JP eboot files.
> 
> @evertonstz do you happen to know what encoding those use? I'm gonna test/look for possible encodings in the meantime.

For every Asian language the default nowdays is UTF-8, so that's not the problem. Also, I tweaked the code a little to remove the exceptions and there's no decoding error. In fact, [pynps](https://github.com/evertonstz/pyNPS) will show Japanese characters (as long as your terminal can handle it ofc), it's all done in utf-8.

EDIT: opps, didn't saw your last comment before posting

**Comment by BertrandHustle** [comment]
@evertonstz just pushed the issue_1 branch which should fix this, could you pull it and test? 

I hit this in my env but i think it's because my terminal isn't set up properly: 
`PermissionError: [WinError 5] Access is denied: '.\\NPJJ00773' -> '.\\ぷよぷよBOX'`

The name parsing appears to be working correctly though.

**Comment by evertonstz** [comment]
Can confirm it [works](https://imgur.com/a/EQS0whk). 
Make sure to check https://github.com/BertrandHustle/psx_scraper/pull/2 as having this untested could mess with the folders for PSP EBOOT games in case a user use this kind of file type.

**Comment by BertrandHustle** [comment]
Fixed in latest merge.
