### ISSUE TITLE
Colons are not removed when renaming games

### ISSUE THREAD

**Issue by BertrandHustle** [BertrandHustle/psx_scraper#6]
`OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '.\\NPUJ00067' -> '.\\Castlevania®:Symphony'`

Unsure if the ® needs to be removed as well, but colon is a known illegal char in Windows.

**Comment by BertrandHustle** [comment]
fixed by 1d8d72f

**Comment by BertrandHustle** [comment]
@evertonstz you may want to pull in this change

**Comment by evertonstz** [comment]
Once I get back working on pynps I'll be sure to pull it. Thanks for the heads up.

Cheers!
